version: "3.3"

services:
  traffic:
    image: gotwaygateway/traffic:v0.0.1
    environment:
      - ENV=production
      - LOG_LEVEL=debug
      - GOTWAY_HOST=gotway.duckdns.org:9111
      - CATALOG_HOST=catalog.gotway.duckdns.org:9111
      - STOCK_HOST=stock.gotway.duckdns.org:9111
      - CLIENT_TIMEOUT=10
      - NUM_WORKERS=5
      - NUM_CLIENTS=2
      - REQUEST_INTERVAL=30
      - TLS=true
